[package]
name = "controller"
version = "0.10.3"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"
default-run = "controller"
license = "Apache-2.0"
publish = false

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[[bin]]
doc = false
name = "crdgen"
path = "src/crdgen.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[features]
default = []
telemetry = []

[dependencies]
actix-rt = "2.2.0"
actix-web = "4.0.0-beta.8"
futures = "0.3.16"
tokio = { version = "1.9.0", features = ["macros"] }
kube = { version = "0.59.0", features = ["derive"] }
kube-runtime = "0.59.0"
k8s-openapi = { version = "0.13.0", features = ["v1_20"], default-features=false }
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
chrono = { version = "0.4.19", features = ["serde"] }
thiserror = "1.0.26"
schemars = { version = "0.8.3", features = ["chrono"] }
serde_yaml = "0.8.17"
maplit = "1.0.2"
tracing = "0.1.26"
tracing-subscriber = { version = "0.2.19", features = ["json"] }
tracing-opentelemetry = "0.14.0"
opentelemetry = { version = "0.16.0", features = ["trace", "rt-tokio"] }
opentelemetry-otlp = { version = "0.9.0", features = ["tokio"] }
prometheus = "0.12.0"

# exemplar support (broken atm)
#prometheus = { git = "https://github.com/clux/rust-prometheus.git", rev = "c9f7ea9652e27cd2d872937c5efbe72f20db0d5e" }

# local dev
#kube = { path = "../kube-rs/kube", features = ["derive"] }
#kube-runtime = { path = "../kube-rs/kube-runtime" }
#kube = { git = "https://github.com/kube-rs/kube-rs.git", rev = "af80a56c4c5952ee270fdba2845498616ba69b2d", features=["derive"] }
#kube-runtime = { git = "https://github.com/kube-rs/kube-rs.git", rev = "af80a56c4c5952ee270fdba2845498616ba69b2d" }
#prometheus = { path = "../rust-prometheus" }
